### PR TITLE
Fix name resolution failures when `Inc`/`Dec` are invoked on pointers

### LINKED ISSUE #141: Name resolution failures when `Inc` and `Dec` are invoked on pointers
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.0.0

### SonarQube version

10.3

### Issue description

`Inc` and `Dec` can be used on typed pointers, but the analyer currently only handles the case where the first argument is an ordinal type.

```java
routine("Dec").varParam(ANY_ORDINAL).param(type(INTEGER)).required(1).returns(type(INTEGER));
routine("Inc").varParam(ANY_ORDINAL).param(type(INTEGER)).required(1);
```

An additional overload is needed for `Inc` and `Dec` that accepts typed pointers.

### Steps to reproduce

See code example.

### Minimal Delphi code exhibiting the issue

```pas
procedure Test(P: PByte);
var
  I: Integer; // UnusedLocalVariable issue will be raised here
begin
  I := 5;
  Inc(P, I);
end;
```

### PR DESCRIPTION
**Pull request by Cirras**
This PR adds a new `TYPED_POINTER` overload to the `Inc` and `Dec` intrinsic signatures.

Fixes #141.

### CODE REVIEW

File: delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcher.java [hunk 1]
```diff
@@ -41,6 +41,11 @@ public final class IntrinsicArgumentMatcher extends TypeImpl {
           "<ordinal>",
           type -> type.isInteger() || type.isBoolean() || type.isEnum() || type.isChar());
 
+  public static final Type ANY_TYPED_POINTER =
+      new IntrinsicArgumentMatcher(
+          "<typed pointer>",
+          type -> type.isPointer() && ((PointerType) type).dereferencedType().size() != 0);
```
Comment (fourls) [inline delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcher.java:47]: Is there a reason you're using `dereferencedType().size() != 0` instead of `dereferencedType().isUntyped()`?

File: delphi-frontend/src/test/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcherTest.java [hunk 2]
```diff
@@ -83,6 +84,14 @@ void testAnyOrdinal() {
     assertThat(matches(ANY_ORDINAL, FACTORY.getIntrinsic(IntrinsicType.STRING))).isFalse();
   }
 
+  @Test
+  void testAnyTypedPointer() {
+    Type typedPointer = FACTORY.pointerTo("PInteger", FACTORY.getIntrinsic(IntrinsicType.INTEGER));
+    assertThat(matches(ANY_TYPED_POINTER, typedPointer)).isTrue();
+    assertThat(matches(ANY_TYPED_POINTER, FACTORY.nilPointer())).isFalse();
+    assertThat(matches(ANY_TYPED_POINTER, FACTORY.nilPointer())).isFalse();
```
Comment (fourls) [inline delphi-frontend/src/test/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcherTest.java:92]: Duplicate line - did you mean to test `FACTORY.untypedPointer()` in the second case here?

**Review by fourls — COMMENTED** [review]
Just a few little comments.

File: delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcher.java (hunk 1 above)
Comment (fourls) [reply delphi-frontend/src/main/java/au/com/integradev/delphi/type/intrinsic/IntrinsicArgumentMatcher.java:47]: I see this would fail in the nil pointer case - in that case, maybe the following?
It is unintuitive to me that a size of 0 means "untyped or nil" - especially since size doesn't really make sense in these scenarios. I still think it would be good to have it be more explicit.

```java
type -> type.isPointer() && !((PointerType) type).dereferencedType().isUntyped() && !((PointerType) type).isNilPointer());
```

File: delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedLocalVariableCheckTest.java [hunk 3]
```diff
@@ -211,4 +213,24 @@ void testUnusedArgumentShouldNotAddIssue() {
                 .appendImpl("end;"))
         .verifyNoIssues();
   }
+
+  // See: https://github.com/integrated-application-development/sonar-delphi/issues/141
```
[the remark this answers is not in the document]
Comment (Cirras) [reply delphi-checks/src/test/java/au/com/integradev/delphi/checks/UnusedLocalVariableCheckTest.java:217]: This one is a regression test, and really only exists to ensure that #141 is not reintroduced in the future.

**Review by fourls — APPROVED** [review]
Looks good!
