### PR TITLE
Fix cast exception when parsing fully qualified attributes

### LINKED ISSUE #213: ClassCastException on qualified attribute references
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.4.0

### SonarQube version

10.4.1

### Issue description

The following error occurs on source code containing fully qualified attribute references.
```
java.lang.ClassCastException: class au.com.integradev.delphi.symbol.occurrence.NameOccurrenceImpl cannot be cast to class au.com.integradev.delphi.symbol.occurrence.AttributeNameOccurrenceImpl (au.com.integradev.delphi.symbol.occurrence.NameOccurrenceImpl and au.com.integradev.delphi.symbol.occurrence.AttributeNameOccurrenceImpl are in unnamed module of loader org.sonar.classloader.ClassRealm @57abad67
```

### Steps to reproduce

Scan the following code example.

### Minimal Delphi code exhibiting the issue

```pas
uses
  REST.Json.Types, Classes;

type
  TTest = class(TInterfacedPersistent)
  private
    [REST.Json.Types.JSONMarshalledAttribute(False)]
    FTest: Integer;
  public
    property Test: Integer read FTest write FTest;
  end;
```

### PR DESCRIPTION
**Pull request by fourls**
This PR fixes a `ClassCastException` that occurs when parsing fully qualified attribute references.

Fixes #213

### CODE REVIEW

**Comment by zaneduffield** [comment]
We should probably add a test that covers this case, to prevent regressions.

**Comment by fourls** [comment]
I agree - happy to hear recommendations about how to test this change. Usually these sorts of things are in `DelphiSymbolExecutorTest`, but the API for these tests doesn't let you assert occurrences across units, so it would need a change to the way these tests work.

File: delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java [hunk 1]
```diff
@@ -664,9 +664,9 @@ private static boolean isDynamicArrayReference(Type type) {
     return type.isClassReference() && ((ClassReferenceType) type).classType().isDynamicArray();
   }
 
-  private void readPossibleUnitNameReference(NameReferenceNode node) {
+  private void readPossibleUnitNameReference(NameReferenceNode node, boolean inAttribute) {
```
Comment (Cirras) [inline delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java:667]: Let's call it `attribute` to be consistent with the parameter name in `readNameReference`.

**Review by Cirras — CHANGES_REQUESTED** [review]

File: delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java (hunk 1 above)
Comment (fourls) [reply delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java:667]: I actually regret naming that parameter `attribute`, I feel like it's an unexpected name for a boolean to have. I've changed it instead to be consistently `inAttribute`, what do you think of that?

Comment (Cirras) [reply delphi-frontend/src/main/java/au/com/integradev/delphi/symbol/resolve/NameResolver.java:667]: Fine by me.

**Review by Cirras — APPROVED** [review]
Looks good to me!
