### PR TITLE
Handle empty anonymous methods in `EmptyRoutine` instead of `EmptyBlock`

### LINKED ISSUE #315: EmptyBlock raises issue on empty anonymous methods, but EmptyRoutine does not
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.11.0

### SonarQube version

_No response_

### Issue description

EmptyBlock currently raises an issue on an empty anonymous method, while EmptyRoutine (which should) does not.

For example, the following raises a single EmptyBlock issue:

```
MyProcedure := procedure begin
    // I am empty for a reason!
  end;
```

This should be ignored by EmptyBlock, since the description states:

> **Exceptions**
> * Empty routine bodies (covered by the EmptyRoutine rule)

EmptyRoutine, on the other hand, should pick this up.

### Steps to reproduce

Scan the following code with SonarDelphi:

```delphi
unit Test;

interface

implementation

uses System.SysUtils;

function GetDummyProc: TProc;
begin
  Result := procedure begin
      // I am empty for a reason
    end;
end;

end.
```

### Minimal Delphi code exhibiting the issue

_No response_

### PR DESCRIPTION
**Pull request by Cirras**
This PR excludes anonymous methods from `EmptyBlock` and flags them in `EmptyRoutine` instead.

Fixes #315.

### CODE REVIEW

File: delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyRoutineCheck.java [hunk 1]
```diff
@@ -42,6 +44,18 @@ public DelphiCheckContext visit(RoutineImplementationNode routine, DelphiCheckCo
     return super.visit(routine, context);
   }
 
+  @Override
+  public DelphiCheckContext visit(AnonymousMethodNode anonymousMethod, DelphiCheckContext context) {
+    if (anonymousMethod.isEmpty() && shouldAddViolation(anonymousMethod)) {
```
Comment (fourls) [inline delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyRoutineCheck.java:49]: It seems odd to have `anonymousMethod.isEmpty()`, one of the two criteria for whether a violation should be added, outside of `shouldAddViolation`. Could we refactor so that this is inside `shouldAddViolation`? Same with the existing `RoutineImplementationNode` code.

File: CHANGELOG.md [hunk 2]
```diff
@@ -18,6 +18,8 @@ and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0
   - Library path (`DelphiLibraryPath`/`DelphiTranslatedLibraryPath`)
   - Browsing path (`DelphiBrowsingPath`)
   - Standard library
+- Empty anonymous methods are now ignored in `EmptyBlock`.
+- Empty anonymous methods are now flagged in `EmptyRoutine`.
```
Comment (fourls) [inline CHANGELOG.md:22]: API additions to `AnonymousMethodNode` should be mentioned in the changelog.

File: delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AnonymousMethodNode.java [hunk 3]
```diff
@@ -41,4 +41,8 @@ public interface AnonymousMethodNode extends ExpressionNode {
   boolean isFunction();
 
   boolean isProcedure();
+
+  CompoundStatementNode getStatementBlock();
+
+  boolean isEmpty();
```
Comment (fourls) [inline delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AnonymousMethodNode.java:47]: What's your reasoning for having `isEmpty()` as a separate function on `AnonymousMethodNode`, when an API consumer could just use the more declarative `getStatementBlock().isEmpty()`?

**Review by fourls — CHANGES_REQUESTED** [review]
Looks pretty good! I have a couple of comments.

File: delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AnonymousMethodNode.java (hunk 3 above)
Comment (Cirras) [reply delphi-frontend/src/main/java/org/sonar/plugins/communitydelphi/api/ast/AnonymousMethodNode.java:47]: Symmetry with the `RoutineNode` API, mostly.

File: CHANGELOG.md (hunk 2 above)
Comment (Cirras) [reply CHANGELOG.md:22]: Good catch, knew I was forgetting something!

File: delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyRoutineCheck.java (hunk 1 above)
Comment (Cirras) [reply delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyRoutineCheck.java]: Done.

File: delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyRoutineCheck.java [hunk 4]
```diff
@@ -59,4 +76,11 @@ private static boolean shouldAddViolation(RoutineImplementationNode routine) {
         && !declaration.hasDirective(RoutineDirective.VIRTUAL)
         && !InterfaceUtils.implementsMethodOnInterface(declaration);
   }
+
+  private static boolean shouldAddViolation(AnonymousMethodNode anonymousMethod) {
+    if (!anonymousMethod.isEmpty()) {
+      return false;
+    }
+    return anonymousMethod.getStatementBlock().getComments().isEmpty();
```
Comment (fourls) [inline delphi-checks/src/main/java/au/com/integradev/delphi/checks/EmptyRoutineCheck.java:84]: This can be a single statement:
```suggestion
  return anonymousMethod.isEmpty() && anonymousMethod.getStatementBlock().getComments().isEmpty();
```

**Review by fourls — CHANGES_REQUESTED** [review]
Just one note. Looks good otherwise.

**Review by fourls — APPROVED** [review]
Looks good!
