### PR TITLE
Fix name resolution failures around type helpers for weak aliases

### LINKED ISSUE #104: Variable being passed as untyped out parameter is not noticed as being initialized
### Prerequisites

- [X] This bug is in SonarDelphi, not SonarQube or my Delphi code.
- [X] This bug has not already been reported.

### SonarDelphi version

1.0.0

### SonarQube version

10.3.0.82913 Community Edition

### Issue description

SonarDelphi raises `community-delphi:VariableInitialization` on the following code (Spring.ValueConverters.pas line 1540 - from 2.0.0 tag)

```
function TDateToStringConverter.DoConvertTo(const value: TValue;
  const targetTypeInfo: PTypeInfo; const parameter: TValue): TValue;
var
  format: TFormatSettings;
begin
  if not parameter.IsEmpty and parameter.TryAsType(TypeInfo(TFormatSettings), format) then
  begin
    case targetTypeInfo.Kind of
      tkString, tkUString:
        Result := TValue.From<string>(DateToStr(value.AsExtended, format)); // <-
```

The logic about this code is that via `parameter` a `TFormatSettings` will be passed and TryAsType has this signature:

`function TValueHelper.TryAsType(typeInfo: PTypeInfo; out target): Boolean;` - when it returns true then the out parameter is being filled. Since the type is being passed via the PTypeInfo parameter the out needs to be typeless.

### Steps to reproduce

Running SonarDelphi on Spring4D 2.0.0

### Minimal Delphi code exhibiting the issue

_No response_

### PR DESCRIPTION
**Pull request by Cirras**
Internally, we map `Type` -> `HelperType` when doing helper lookups in a given scope.

The analyzer models weak alias types by generating a transparent wrapper around the aliased type. It looks and behaves exactly like the aliased type, but the two type objects are not **equal** to each other.

The source of truth about a type's identity is the image, so the solution here is to simply map `<type image>` -> `HelperType` instead.

Fixes #104 and #108.

### CODE REVIEW

File: delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/helpers/WeakAliasHelper.pas [hunk 1]
```diff
@@ -0,0 +1,32 @@
+unit Simple;
+
+interface
+
+type
+  TFoo = record
+    procedure Bar;
+  end;
+
+  TFooHelper = record helper for TFoo
```
Comment (fourls) [inline delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/helpers/WeakAliasHelper.pas:10]: I think you forgot to make this a weak alias 😄 I checked and this test already passes on master.

Updating this file to match the below does fail on master and pass in this branch, though, so the main code change is all good.
```delphi
type
  TFoo = record
    procedure Bar;
  end;

  TFooAlias = TFoo;

  TFooHelper = record helper for TFooAlias
    procedure Bar;
  end;
```

File: delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/helpers/WeakAliasHelper.pas [hunk 2]
```diff
@@ -0,0 +1,32 @@
+unit Simple;
```
Comment (fourls) [inline delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/helpers/WeakAliasHelper.pas:1]: This unit header should be named `WeakAliasHelper` to match the filename.

**Review by fourls — COMMENTED** [review]
Main code change looks good! Only thing is that the test does not cover the change.

File: delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/helpers/WeakAliasHelper.pas (hunk 1 above)
Comment (Cirras) [reply delphi-frontend/src/test/resources/au/com/integradev/delphi/symbol/helpers/WeakAliasHelper.pas:10]: Whoops, I'm a dork.
Fixing that...

**Review by fourls — APPROVED** [review]
All good now! I'll merge once the checks pass.
